CREATE TABLE "monsters" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "meta" TEXT NOT NULL,
    "armor_class" TEXT NOT NULL,
    "hit_points" TEXT NOT NULL,
    "speed" TEXT NOT NULL,
    "str" TEXT NOT NULL,
    "str_mod" TEXT NOT NULL,
    "dex" TEXT NOT NULL,
    "dex_mod" TEXT NOT NULL,
    "con" TEXT NOT NULL,
    "con_mod" TEXT NOT NULL,
    "int" TEXT NOT NULL,
    "int_mod" TEXT NOT NULL,
    "wis" TEXT NOT NULL,
    "wis_mod" TEXT NOT NULL,
    "cha" TEXT NOT NULL,
    "cha_mod" TEXT NOT NULL,
    "saving_throws" TEXT,
    "skills" TEXT,
    "senses" TEXT,
    "languages" TEXT,
    "challenge" TEXT NOT NULL,
    "traits" TEXT,
    "actions" TEXT,
    "legendary_actions" TEXT,
    "img_url" TEXT
);